token: "qDoy0VWAB7GxRZor"    # lichess OAuth2 Token
url: "https://lichess.org/"  # lichess base URL
good_luck_messages: # messages sent to chat when game begins
  - "good luck"
good_game_message: "good game" # message sent to chat when game finishes

engine:                      # engine settings
  dir: "./engines/"          # dir containing engines, relative to this project
  name: "stockfish"        # binary name of the engine to use
  protocol: "uci"            # "uci" or "xboard"

  polyglot:
    enabled: false           # activate polyglot book
    books:                   # books
      - "engines/books/Book.bin"
      - "engines/books/default.bin"
      - "engines/books/codekiddy.bin"
      - "engines/books/DCbook_large.bin"
      - "engines/books/Elo2400.bin"
      - "engines/books/final-book.bin"
      - "engines/books/gavibook.bin"
      - "engines/books/gavibook-small.bin"
      - "engines/books/gm2600.bin"
      - "engines/books/komodo.bin"
      - "engines/books/KomodoVariety.bin"
      - "engines/books/Performance.bin"
      - "engines/books/varied.bin"
    max_depth: 50             # half move max depth
    min_weight: 1            # selects move with highest weight but not below this value
    random: true             # selects move randomly; otherwise select the best but not below the min_weight
  uci_options:               # arbitrary UCI options passed to the engine
    Move Overhead: 100       # increase if your bot flags games too often
    Threads: 6               # max CPU threads the engine can use
    Hash: 256                # max memory (in megabytes) the engine can allocate
# xboard_options:            # arbitrary xboard options passed to the engine
#   cores: "4"
#   memory: "4096"
#   egtpath:                 # dir containing egtb, relative to this project
#     gaviota: "Gaviota path"
#     nalimov: "Nalimov Path"
#     scorpio: "Scorpio Path"
#     syzygy: "Syzygy Path"
# lczero:                    # lczero specific settings
#   weights: "engines/latest.txt" # weights file path
#   threads: 1               # max CPU threads the engine can use
#   gpu: 0                   # which GPU to use
#   tempdecay: 15            # ?
#   noise: true              # ?
  silence_stderr: false      # some engines (yes you, leela) are very noisy

max_concurrent_games: 1      # number of games to play simultaneously
abort_time: 20               # time to abort a game in seconds when there is no activity

challenge:                   # incoming challenges
  sort_by: "first"            # possible values: "best", "first"
  accept_bot: true          # accepts challenges coming from other bots
  variants:                  # chess variants to accept (http://lichess.org/variant)
    - standard
    - fromPosition
#   - antichess
#   - atomic
#   - chess960
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  time_controls:             # time controls to accept
#   - ultraBullet
#   - bullet
#   - blitz
#   - rapid
    - classical
#   - correspondence
  modes:                     # game modes to accept
#   - casual                 # unrated games
    - rated                  # rated games - must comment if the engine doesn't try to win
